### ISSUE TITLE
Tarayıcı Çözünürlük

### ISSUE THREAD

**Issue by fatihhoca** [fatihhoca/atiba#1]
Çözünürlüğü düşük ekranlarda ekranın sağ üstünde açılan öğrenci bilgi balonu açılması gereken göz icon'larının önüne geldiği için bazı veriler açılamıyor.

Yakında çözeriz :)

**Comment by recep2005** [comment]
Sorun giderildi

**Comment by fatihhoca** [comment]
Eline sağlık hocam 👍

**Comment by recep2005** [comment]
Tarayıcı %70 sorun çıkarmuış sizede ve o bup ortadan kaşldırmanın yolunu bulmuşsunuz elinize sağlık.
