### ISSUE TITLE
cinsiyet bilgisi çekmek

### ISSUE THREAD

**Issue by recep2005** [fatihhoca/atiba#10]
Öğrenci cinsiyet bilgisi alma

**Comment by recep2005** [comment]
Öğrenci cinsiyet ve Uyruk bilgisini çelme özellği eklendi.
Bu işem sırasında yeni hazılanan listbox satır ekleme özelliği denenedi.

**Comment by fatihhoca** [comment]
Akşam deneme yapıp sürüm çıkarım hocam
Eline sağlık
