### ISSUE TITLE
Veri çekmede mükerrer tıklama olduğunda tekrar baştan tüm verileri çekiyor.

### ISSUE THREAD

**Issue by recep2005** [fatihhoca/atiba#4]
-İstenilen satırdan başlayarak veri çekmesinin sağlanabilir.
(dr değişkeni) 
(   foreach (DataGridViewRow dr in dataGridView1.Rows) )

**Comment by recep2005** [comment]
Bu bud da düzeltildi. Artık internet kesilince yada başka bir hatadan yarım kalan veri çekme işlemi veya kullnıcı yanlışlıkla tekrar veri çek butonuna basarsa  kaldğın yerden devam etsinmi diye soruyor evette kaldığı yerden hayırda baştan veri çekiyor.

**Comment by fatihhoca** [comment]
Eline sağlık hocam 👍
Kısa bir deneme yapıp güncelleme çıkacağım

**Comment by fatihhoca** [comment]
Hocam veri çekimi devam ederken internet sayfasını kapattım işlem yarım kaldı 
Sonra programı kapatmadan tekrar sayfayı açıp verileri çek dedim ve işlem kaldığı yerden devam etsinmi dedim
Devam etsin diyince yeni veri çekmiyor
Hızlıca progressbar ilerleyip bitiyor

sen deneme yapmışmıydın ?
yoksa ben yanlışmı deniyorum?

**Comment by fatihhoca** [comment]
Aşağıdaki gibi kodları düzenlendiğimde çalışıyor
Finally bloğunda satir=endingRow; olunca her şartta ikisi eşit gidiyor o yüzden anlamsız kalıyor
endingRow değerini try bloğunun bitiminde yani hiç bir sorun olmadan veri alımı bitince arttırdım sanki düzgün çalıştı

Senin yapmak istediğini doğrumu anladım emin değilim
Sende kontrol edersen sevinirim

![image](https://user-images.githubusercontent.com/35226485/209448217-b04e44b1-45b3-4b10-9da3-9d304626f672.png)

**Comment by recep2005** [comment]
amacım satır bitince biten satırın sayısını endingrow a almak bu sayede kaldığı yeri hatırlasın. Söyle yaptım daha iyi oldu gibi. Kontrol edersen sevinirim.Ayrıca barın başlangıc değerini de satır değişkenine eşitledim. o da tekrar basımda düzgün çalıştı. Öncekinde saki bir şey eksik gibiydi.
![Screenshot_1](https://user-images.githubusercontent.com/61024527/209455570-8261b86b-ba23-4473-893d-c134ac663731.png)

**Comment by fatihhoca** [comment]
Tamamdır hocam
Bu şekilde dener yeni sürüm çıkarım 👍
